import user1 from "../../../assets/img/img1.png";
import user2 from "../../../assets/img/img2.png";
import user3 from "../../../assets/img/img3.png";
import UserItem from "entities/user-item";
import groupIcon from "../../../assets/img/gpIcon.png";

export default class ContactsMockData {
  public static contacts: UserItem[] = [
    {
      id: 1001,
      title: "sahar joon",
      phoneNumber: "09120286220",
      status: "last seen recently",
      avatarURl: user2,
      textPlaceHolder: "SB",
      type: "User",
      userName: "sahar khanum2",
    },
    {
      id: 1,
      phoneNumber: "09120286220",
      userName: "sahar khanum",
      title: "sahar",
      status: "online",
      avatarURl: user3,
      textPlaceHolder: "SB",
      type: "User",
    },
    {
      id: 2,
      phoneNumber: "091205267870",
      userName: "sina beh2",
      title: "sina",
      status: "online",
      avatarURl: "",
      textPlaceHolder: "SB",
    },
    {
      id: 3,
      phoneNumber: "0912028765",
      userName: "mehdi.beh",
      title: "mehdi behmanesh",
      status: "last seen recently",
      avatarURl: "",
      textPlaceHolder: "SB",
    },
    {
      id: 4,
      phoneNumber: "09120286220",
      userName: "sahar khanum3",
      title: "sahar",
      status: "online",
      avatarURl: user3,
      textPlaceHolder: "SB",
    },
    {
      id: 5,
      phoneNumber: "091205267870",
      userName: "sina beh",
      title: "sina",
      status: "online",
      avatarURl: "",
      textPlaceHolder: "SB",
    },
    {
      id: 1002,
      title: "aghaye behmanesh",
      phoneNumber: "09124567665",
      status: "Online",
      avatarURl: user1,
      textPlaceHolder: "AG",
      type: "User",
      userName: "behmaneshpour",
    },
    {
      id: 1003,
      title: "maman",
      phoneNumber: "09120286220",
      status: "2 weeks ago",
      avatarURl: user2,
      textPlaceHolder: "SS",
      type: "User",
      userName: "s.saadvandi",
    },
    {
      id: 1004,
      title: "ali nooshabadi",
      phoneNumber: "09128727722",
      status: "11:57AM",
      avatarURl: user3,
      textPlaceHolder: "AN",
      type: "User",
      userName: "a.nooshabadi",
    },
    {
      id: 1005,
      title: "baba",
      phoneNumber: "09128727722",
      status: "10:07AM",
      avatarURl: user1,
      textPlaceHolder: "MB",
      type: "User",
      userName: "m.behbahani",
    },
    {
      id: 1006,
      title: "Amir Bp",
      phoneNumber: "09125832660",
      status: "13:19 AM",
      avatarURl: user1,
      textPlaceHolder: "AB",
      type: "User",
      userName: "Amir.BP",
    },
    {
      id: 1007,
      title: "Abbas Agha",
      phoneNumber: "234567889",
      status: "last seen recently",
      textPlaceHolder: "AB",
      type: "User",
      userName: "AbasAgha",
    },
    {
      id: 1008,
      title: "digikala",
      phoneNumber: "888888822",
      status: "last seen recently",
      avatarURl: user2,
      textPlaceHolder: "DK",
      type: "User",
      userName: "digikala",
    },
    {
      id: 1009,
      title: "Mojdeeeeee",
      phoneNumber: "09129619009",
      userName: "dhskjdh3434hjh",
      status: "online",
      avatarURl: user1,
      textPlaceHolder: "MK",
      type: "User",
    },
    {
      id: 1010,
      title: "fasanghari",
      phoneNumber: "09120286770",
      status: "last seen recently",

      textPlaceHolder: "FA",
      type: "Group",
      userName: "fasanghariTop",
    },
    {
      id: 1011,
      title: "Behbahania",
      phoneNumber: "09120286770",
      status: "last seen recently",
      avatarURl: groupIcon,
      textPlaceHolder: "BE",
      type: "Group",
      userName: "behbahaniha",
    },
    {
      id: 1012,
      title: "sahar joon",
      phoneNumber: "09120286220",
      status: "last seen recently",
      avatarURl: user2,
      textPlaceHolder: "SB",
      type: "User",
      userName: "sahar.beh",
    },
    {
      id: 1013,
      title: "solmaz",
      phoneNumber: "09120286220",
      status: "last seen recently",
      avatarURl: user2,
      textPlaceHolder: "SB",
      type: "User",
      userName: "solmaz.sh",
    },
    {
      id: 1014,
      title: "sanaz khanum",
      phoneNumber: "09120286770",
      status: "last seen recently",
      avatarURl: user3,
      textPlaceHolder: "SH",
      type: "User",
      userName: "sh.hosseini",
    },
    {
      id: 10,
      phoneNumber: "0912028765",
      userName: "@family",
      title: "Family",
      status: "last seen recently",
      avatarURl: groupIcon,
      textPlaceHolder: "FA",
      type: "Group",
    },
    {
      id: 7,
      phoneNumber: "0912028765",
      userName: "gholi.loos",
      title: "Gholi jooon",
      status: "last seen recently",
      avatarURl: "",
      textPlaceHolder: "GH",
      type: "User",
    },
    {
      id: 8,
      phoneNumber: "0912028765",
      userName: "Asghar",
      title: "Asghar",
      status: "last seen recently",
      avatarURl: "",
      textPlaceHolder: "AS",
      type: "User",
    },
    {
      id: 9,
      phoneNumber: "091233765",
      userName: "@hasan",
      title: "hasan",
      status: "last seen recently",
      avatarURl: "",
      textPlaceHolder: "HA",
      type: "User",
    },
  ];
}
