import img from "../../../assets/img/sahar.jpg";
import ChatListItem from "../chat-list-item";

export default class ChatListMockData {
  public static Comments: ChatListItem[] = [
    {
      user: {
        id: 1,
        phoneNumber: "09120286220",
        userName: "sahar khanum",
        title: "sahar",
        status: "online",
        avatarURl: img,
        textPlaceHolder: "SB",
      },
      lastMessage: "Hello",
      lastMessageTime: "now",
    },
    {
      user: {
        id: 2,
        phoneNumber: "091205267870",
        userName: "sina beh",
        title: "sina",
        status: "online",
        avatarURl: "",
        textPlaceHolder: "SB",
      },
      lastMessage: "Hello",
      lastMessageTime: "sep 10",
      newMessageCount: 2,
    },
    {
      user: {
        id: 3,
        phoneNumber: "0912028765",
        userName: "mehdi.beh",
        title: "mehdi behmanesh",
        status: "last seen recently",
        avatarURl: "",
        textPlaceHolder: "SB",
      },
      lastMessage: "salam aziizam khubi?",
      lastMessageTime: "11:18 AM",
      newMessageCount: 3,
    },
    {
      user: {
        id: 4,
        phoneNumber: "09120286220",
        userName: "sahar khanum",
        title: "sahar",
        status: "online",
        avatarURl: img,
        textPlaceHolder: "SB",
      },
      lastMessage: "Hello",
      lastMessageTime: "now",
      newMessageCount: 5,
    },
    {
      user: {
        id: 5,
        phoneNumber: "091205267870",
        userName: "sina beh",
        title: "sina",
        status: "online",
        avatarURl: "",
        textPlaceHolder: "SB",
      },
      lastMessage: "Hello",
      lastMessageTime: "sep 10",
      newMessageCount: 6,
    },
    {
      user: {
        id: 6,
        phoneNumber: "0912028765",
        userName: "@family",
        title: "Family",
        status: "last seen recently",
        avatarURl: "",
        textPlaceHolder: "FA",
        type: "Group",
      },
      lastMessage: "salam aziizam khubi?",
      lastMessageTime: "11:18 AM",
    },
    {
      user: {
        id: 7,
        phoneNumber: "0912028765",
        userName: "@family",
        title: "Family",
        status: "last seen recently",
        avatarURl: "",
        textPlaceHolder: "FA",
        type: "Group",
      },
      lastMessage: "salam aziizam khubi?",
      lastMessageTime: "11:18 AM",
      newMessageCount: 10,
    },
    {
      user: {
        id: 8,
        phoneNumber: "0912028765",
        userName: "@family",
        title: "Family",
        status: "last seen recently",
        avatarURl: "",
        textPlaceHolder: "FA",
        type: "Group",
      },
      lastMessage: "salam aziizam khubi?",
      lastMessageTime: "11:18 AM",
    },
    {
      user: {
        id: 9,
        phoneNumber: "0912028765",
        userName: "@family",
        title: "Family",
        status: "last seen recently",
        avatarURl: "",
        textPlaceHolder: "FA",
        type: "Group",
      },
      lastMessage: "salam aziizam khubi?",
      lastMessageTime: "11:18 AM",
      newMessageCount: 10,
    },
    {
      user: {
        id: 10,
        phoneNumber: "0912028765",
        userName: "@family",
        title: "Family",
        status: "last seen recently",
        avatarURl: "",
        textPlaceHolder: "FA",
        type: "Group",
      },
      lastMessage: "salam aziizam khubi?",
      lastMessageTime: "11:18 AM",
    },
  ];
}
